const Map<String, String> en = {
  'shop': 'Shop',
  'bag': 'Bag',
  'email': 'Email',
  'phone': 'Phone',
  'address': 'Address',
  'full_name': 'Full name',
  'show_all': 'Show all',
  'no_products_found': 'No products found',
  'cart_empty': 'Cart is empty',
  'favorite': 'Favorite',
  'profile': 'Profile',
  'my_bag': 'My Bag',
  'login': 'Login',
  'emailOrUsername': 'Email or username',
  'noAccount': 'No account?',
  'details': 'Details',
  'signUp':'Sign up',
  'username': 'Username',
  'password': 'Password',
  'loginButton': 'Login',
  'pleaseLogin': 'Please login first',
  'settings': 'Settings',
  'language': 'Language',
  'english': 'English',
  'mongolian': 'Mongolian',
  'logout': 'Logout',
  'productDetails': 'Product Details',
  'addToCart': 'Add to Cart',
  'removeFromCart': 'Remove from Cart',
  'clearCart': 'Clear Cart',
  'total_price': 'Total Price',
  'yourCartIsEmpty': 'Your cart is empty',
  'areYouSureRemoveAll': 'Are you sure you want to remove all items?',
  'cancel': 'Cancel',
  'clear': 'Clear',
  'buy_all': 'Buy All',
  'quantity': 'Quantity',
  'description': 'Description',
  'category': 'Category',
  'price': 'Price',
  'pleaseLoginFirst': 'Please login first',
  'shopping': 'Shopping',
  'favorites': 'Favorites',
  'pleaseLoginToViewFavorites': 'Please login to view favorites',
  'noFavoritesYet': 'No favorites yet',
  'myFavoriteItems': 'My Favorite Items',

  'noDisplayName': 'No display name',
  'reviews': 'Reviews', 
  'no_reviews': 'No reviews',
  'writeReview': 'Write review', 
  'reviewTitle': 'Review title', 
  'reviewContent': 'Review content', 
  'rating': 'Rating', 
  'fillAllFields': 'Fill all fields', 
  'submitReview': 'Submit review',
  'signUpButton': 'Sign up',
  'confirmPassword': 'Confirm password',
  'alreadyHaveAccount': 'Already have an account?'
}; 