const Map<String, String> mn = {
  'shop': 'Дэлгүүр',
  'bag': 'Сагс',
  'email': 'Имэйл',
  'phone': 'Утас',
  'address': 'Хаяг',
  'full_name': 'Нэр',
  'show_all': 'Бүгдийг харуулах',
  'no_products_found': 'Бүтээгдэхүүн олдсонгүй',
  'favorite': 'Дуртай',
  'profile': 'Профайл',
  'my_bag': 'Миний сагс',
  'login': 'Нэвтрэх',
  'emailOrUsername': 'Имэйл эсвэл хэрэглэгчийн нэр',
  'noAccount': 'Бүтгэлгүй бол:',
  'signUp':'Бүртгүүлэх',
  'username': 'Хэрэглэгчийн нэр',
  'password': 'Нууц үг',
  'details': 'Дэлгэрэнгүй мэдээлэл',
  'loginButton': 'Нэвтрэх',
  'pleaseLogin': 'Эхлээд нэвтэрнэ үү',
  'settings': 'Тохиргоо',
  'language': 'Хэл',
  'english': 'Англи',
  'mongolian': 'Монгол',
  'logout': 'Гарах',
  'productDetails': 'Барааны дэлгэрэнгүй',
  'addToCart': 'Сагсанд нэмэх', 
  'removeFromCart': 'Сагснаас хасах',
  'clearCart': 'Сагс цэвэрлэх',
  'total_price': 'Нийт үнэ',
  'cart_empty': 'Таны сагс хоосон байна',
  'areYouSureRemoveAll': 'Бүх барааг устгахдаа итгэлтэй байна уу?',
  'cancel': 'Болих',
  'clear': 'Цэвэрлэх',
  'buy_all': 'Бүгдийг худалдаж авах',
  'quantity': 'Тоо ширхэг',
  'description': 'Тайлбар',
  'category': 'Ангилал',
  'price': 'Үнэ',
  'pleaseLoginFirst': 'Эхлээд нэвтэрнэ үү',
  'shopping': 'Дэлгүүр',
  'selectLanguage': 'Хэл сонгох',
  'languageChanged': 'Хэл солигдлоо',
  'favorites': 'Дуртай',
  'pleaseLoginToViewFavorites': 'Дуртай зүйлсээ харахын тулд нэвтэрнэ үү',
  'noFavoritesYet': 'Одоогоор дуртай зүйл алга',
  'myFavoriteItems': 'Миний дуртай зүйлс',

  'noDisplayName': 'Нэр харуулахгүй',
  'reviews': 'Сэтгэгдлүүд', 
  'no_reviews': 'Сэтгэгдэл хоосон байна',
  'writeReview': 'Сэтгэгдэл бичих', 
  'reviewTitle': 'Сэтгэгдэл', 
  'reviewContent': 'Сэтгэгдэл', 
  'rating': 'Үнэлгээ', 
  'fillAllFields': 'Бүх талбарыг дүүргэх', 
  'submitReview': 'Сэтгэгдлийг илгээх'
}; 