// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLh5OioShAfkNupOBMn_Syn1sDBC2__0',
    appId: '1:728859450594:web:ba4966870917d4ef3b52bb',
    messagingSenderId: '728859450594',
    projectId: 'bindy-firebase',
    authDomain: 'bindy-firebase.firebaseapp.com',
    storageBucket: 'bindy-firebase.firebasestorage.app',
    measurementId: 'G-2V4C13GKNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dhORA-1eudaWnJPl98Fj0QZm5Xh2XhI',
    appId: '1:728859450594:android:db0b2c0e83ce9c2c3b52bb',
    messagingSenderId: '728859450594',
    projectId: 'bindy-firebase',
    storageBucket: 'bindy-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOZUh9l4D8KP800J9NXvND0PWnWe8H_aE',
    appId: '1:728859450594:ios:d5e3e1ca8c5fde613b52bb',
    messagingSenderId: '728859450594',
    projectId: 'bindy-firebase',
    storageBucket: 'bindy-firebase.firebasestorage.app',
    iosBundleId: 'com.example.shopAppLab13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOZUh9l4D8KP800J9NXvND0PWnWe8H_aE',
    appId: '1:728859450594:ios:d5e3e1ca8c5fde613b52bb',
    messagingSenderId: '728859450594',
    projectId: 'bindy-firebase',
    storageBucket: 'bindy-firebase.firebasestorage.app',
    iosBundleId: 'com.example.shopAppLab13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZLh5OioShAfkNupOBMn_Syn1sDBC2__0',
    appId: '1:728859450594:web:711f8d1bf5482d583b52bb',
    messagingSenderId: '728859450594',
    projectId: 'bindy-firebase',
    authDomain: 'bindy-firebase.firebaseapp.com',
    storageBucket: 'bindy-firebase.firebasestorage.app',
    measurementId: 'G-HGM4F5Y4CJ',
  );
}
